# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Thinking Machine
email: julsoles@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
# theme: minima
# theme: minimal-mistakes-jekyll
# theme: alembic-jekyll-theme
kramdown:
  syntax_highlighter_opts:
    disable: true
  math_engine: mathjax
include: ['_pages']
exclude: [vendor]
remote_theme: daviddarnes/alembic
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: DavidDarnes # jekyll-seo-tag > Owners twitter username
author: DavidDarnes # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: David Darnes # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://www.linkedin.com/in/julsoles
    - https://github.com/juliosol
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# 6. Jekyll collections settings
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      image: "/assets/default-social-image.png" # Default image for sharing


# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Alembic" # Site name or title, also used in jekyll-seo-tag
logo: "/site_resources/tropical_logo.png" # Site logo, also used in jekyll-seo-tag

url: "https://juliosol.github.io" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/juliosol/juliosol.github.io"

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Projects
  url: /projects/
- title: About
  url: /about/
#- title: Archive
#  url: /archive/
#- title: Search
#  url: /search/
#- title: Fork Alembic
#  url: https://github.com/daviddarnes/alembic

navigation_footer:
- title: Created by Julio Soldevilla (Using alembic-jekyll-theme)
  #url: https://darn.es

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  #Twitter: https://twitter.com/DavidDarnes
  LinkedIn: https://www.linkedin.com/in/julsoles/
  GitHub: https://github.com/juliosol
  
sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
